### ISSUE TITLE
OSX High-Sierra CTD because of "bind font" failure

### ISSUE THREAD

**Issue by snagar** [sparker256/imgui4xp#5]
Hi,
This issue did not occurred when I tested this Windows and Linux OSes so it is somewhat strange that it only happened in OSX High-Sierra.

**Problem**
When I started X-Plane it crashed after few seconds. My plugin was the culprit.
I debugged the issue using XCode, and found out that the culprit of the issue was this row in ImgWindow.cpp:

`if (iFontAtlas->TexID == nullptr) {`

**Weird behavior**
It seems that the "mFontAtlas" in the constructor is not initialized correctly (which by itself is strange because on <make share> creation it was fine:
`mission.uiImGuiMxpad = std::make_shared<WinImguiMxpad>(left, top, right, bottom, xplm_WindowDecorationSelfDecoratedResizable, xplm_WindowLayerFloatingWindows); `

The CDT happened after "XPluginStart" finished. It seems that the same constructor was called again but without the data needed for mFontAtalas.
Flow:
1. mFontAtlas: not initialized with a value.
2. iFontAtlas pointer is not initialized as result of that:
```
    ImFontAtlas *iFontAtlas = nullptr;
    if (mFontAtlas) {
        mFontAtlas->bindTexture();
        iFontAtlas = mFontAtlas->getAtlas();
    }
```

3. "bind the font" step in the constructor fails and crashes X-Plane:

```
if (mFontAtlas) {
        mFontTexture = static_cast<GLuint>(reinterpret_cast<intptr_t>(io.Fonts->TexID));
    } else {
        if (iFontAtlas->TexID == nullptr) {
            // fallback binding if an atlas wasn't explicitly set.
```
Since mFontAtlas is not initialized the code skips it and uses the: "iFontAtlas->TexID", but that does not make sense since it was not initialized either, hence the crash and the failure to do the "fallback binding".

**Solution/Workaround**
Add test if iFontAtlas is NULL.

`if (iFontAtlas == NULL || iFontAtlas->TexID == nullptr)`

This seem to solve the issue on OSX. It might be a bad workaround and not the root cause, but for now it seem to behave as expected.

Saar

**Comment by TwinFan** [comment]
Next time, it would help if you named file name and line numbers of those lines you identified already.

I think there is a problem in the `ImgWindow::ImgWindow` constructor, which a static code analysis once showed me, but I had it ignored as the usage in the example plugin (and in LiveTraffic where I use similar code) does not trigger it. Without knowing your code it is unclear if that is your problem now.

All your analysis is correct, but not the beginning. The beginning is that if `ImgWindow::sFontAtlas` (a static member) is still `nullptr` by the time the `ImgWindow::ImgWindow` constructor is called, then this `nullptr` is copied into `mFontAtlas` (line 62 of `ImgWindow.xpp`). Then follows what you found: the initialization of `iFontAtlas` in line 69 is also skipped and it stays `nullptr`. Later on, execution will find `mFontAtlas` be `nullptr`, so the `if` in line 118 fails and execution continues in line 121 where `iFontAtlas` is used...which is still `nullptr`. There is no valid path through the code, in which the code section beginning in line 121 could be legally executed. I have no clue why that code is in and how it got tested. (It is [code by kuroneko](https://github.com/xsquawkbox/xsb_public).)

Your suggested fix will avoid the crash. The window will then not have a font atlas. That is ok as long as you only want to use imgui's built-in standard font.

The probably better way is set `ImgWindow::sFontAtlas` _before_ using `ImgWindow`. The example code does that in `configureImgWindow()`, line 171 of `imgui_starter_window.cpp`, and then defines a specific font to use and mixes some icons of another font into that font atlas.

None of that would be MacOS-specific, though. And as all variables involved are properly initialized it would be unclear to me why code that fails in `ImgWindow.cpp:121` due to `iFontAtlas == nullptr` can successfully execute in other OSs.

**Comment by snagar** [comment]
Hi sparker,
Some observation from my plugin:
1. The "configureImgWindow()" is called in my plugin prior to creating the "shared pointer" class (the imgui UI classes).
2. The first time I initialize the ImguiWindow:
    `Mission::uiImGuiMxpad = std::make_shared<WinImguiMxpad>(left, top, right, bottom, xplm_WindowDecorationSelfDecoratedResizable, xplm_WindowLayerFloatingWindows);`
everything looks fine. Meaning the mFontAtlas is initialized correctly and not deleted.
3. Later the constructor is called again, no idea why, and this time there is no value in "mFontAtlas" so it calls the fallback code.

Result:
I can see the "DejaVuSans.ttf" in OSX correctly and no crash present itself.
I do worry that my workaround does not solve the root cause which I'll continue to investigate.

Disclaimer:

1. I did thought that maybe an ASSERT should have been placed there and kick you out of the program, but after doing some
tracing I could not figure out why this occurs hence the workaround. 
On my Linux/Windows this never occurs. 
2. On Linux and Windows I initialize GLEW before calling "configureImgWindow()". In OSX I do not initialize GLEW, I just call "configureImgWindow()".

**Comment by TwinFan** [comment]
Suggest you put a breakpoint into the constructor and debug why and when the constructor is called again (your point 3.).

Are you sure you really need smart pointers (`std::make_shared`)? The examples uses smart pointers because it creates several pointers to several windows in an array, managed by that array. The array is cleared and hence the windows destroyed properly during `XPluginDisable` when such code can still reasonable execute. (Well...thinking about it...the example could even use `unique_ptr`, would probably cause less confusion.)

If you have just one global variable (your `Mission::uiImGuiMxpad` looks like a static one) then I suggest you just use a plain `WinImguiMxpad*` pointer. In a static variable, a shared pointer can't really play the fact that it is _managed_ because the static variable would be destroyed only during library unload when no GUI code can reasonable execute any longer anyway. For proper deletion you should destroy latest from `XPluginDisable`...where you could just call `delete Mission::uiImGuiMxpad`.

**Comment by sparker256** [comment]
I merged in a pull request and somehow this issue got closed so I reopened it just to be sure it should be closed.

**Comment by snagar** [comment]
Hi,

I guess you are correct regarding the pointers, I just followed the example. Well, there are benefits in using these syntax, they clean themselves.

**Comment by sparker256** [comment]
I will close this as it seems to have been resolved with the last PR.
